# Site settings
title: Jüdisch-Christliche Arbeitsgemeinschaft
email: info@jcha.de
description: "Die Jüdisch-Christliche Arbeitsgemeinschaft"
baseurl: ""
url: "http://jcha.de"

# Build settings
markdown: kramdown
permalink: pretty
future: true

# Exclude files from being copied to _site
exclude: [put.sh, Taskfile.yml,"*.env"]
