version: '3'

dotenv: ['custom.env', 'default.env']

vars:
  WORKING_DIRECTORY: '{{.github.workspace | default .PWD}}'
  BUNDLE_PATH: '.vendor'
  ID_UID:
    sh: id -u
  ID_GID:
    sh: id -g
  TARGET: '{{.TARGET | default "_site"}}'

tasks:

  default:
    desc: List the available tasks
    cmds:
      - task -l

  build:
    desc: Build the page from source
    cmds:
      - task: build:docker
        vars:
          LANGUAGE: de
          TARGET: '{{.TARGET}}'

  build:docker:
    desc: Build the page from source using docker
    vars:
      JEKYLL_UID: '{{.JEKYLL_UID | default .ID_UID}}'
      JEKYLL_GID: '{{.JEKYLL_GID | default .ID_GID}}'
      JEKYLL_USER_ARG:
        sh: '[ "$(docker info --format "{{`{{if .Host.Security.Rootless}}true{{end}}`}}")" = "true" ] || echo -u "{{.JEKYLL_UID}}:{{.JEKYLL_GID}}"'
      JEKYLL_IMAGE: ghcr.io/aksw/jekyll-rdf:4.2.4
    cmds:
      - |
        docker run --rm \
        --workdir /workspace \
        -v {{.WORKING_DIRECTORY}}:/workspace:z \
        -e TZ=Europe/Berlin {{.JEKYLL_USER_ARG}} -e BUNDLE_PATH={{.BUNDLE_PATH}} \
        {{.JEKYLL_IMAGE}} jekyll build -d {{.TARGET}}

  upload:docker:
    desc: Update the changes to the server
    aliases: [upload]
    cmds:
      - |
        echo "Update webpage …"
        gio mount sftp://{{.remote_user}}@{{.remote_server}}
        rsync -av --no-times {{.WORKING_DIRECTORY}}/{{.TARGET}}/ /run/user/{{.ID_UID}}/gvfs/sftp:host={{.remote_server}},user={{.remote_user}}{{.remote_path}}
        gio mount --unmount sftp://{{.remote_user}}@{{.remote_server}}

  serve:
    desc: Serve the locally built site
    cmds:
      - python -m http.server --directory {{.TARGET}}

  clean:
    desc: Clean up temporary direcotries
    cmds:
      - rm -r .vendor .jekyll-cache .bundle
